version: '3.8'

x-db-variables: &db-variables
 MYSQL_DATABASE: bugle
 MYSQL_ROOT_PASSWORD: root
 MYSQL_USER: jjjjr
 MYSQL_PASSWORD: spiderman
 MYSQL_PORT: 3306
 
services:

  NEWSPAPER:
    build: .
    image: newspaper-but-worse
    restart: on-failure
    depends_on:
     - mysql
    ports:
     - 8080:8080
    environment:
      SPRING_DATASOURCE_DATABASE: bugle
      SPRING_DATASOURCE_ROOT_PASSWORD: root
      SPRING_DATASOURCE_USER: jjjjr
      SPRING_DATASOURCE_PASSWORD: spiderman
      SPRING_DATASOURCE_PORT: 3306
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bugle?useSSL=false&allowPublicKeyRetrieval=true

  mysql:
    image: mysql:8.0
    ports:
     - 3306:3306
    environment:
     <<: *db-variables

volumes:
  bugle-db:
