version: '3.8'
x-db-variables: &db-variables
 MYSQL_DATABASE: bugle
 MYSQL_ROOT_PASSWORD: root
 MYSQL_USER: jjjjr
 MYSQL_PASSWORD: spiderman
services: 
  NEWSPAPER:
    build: .
    image: newspaper-but-worse:latest
    ports:
     - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bugle
      <<: *db-variables
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.26
    volumes:
      - bugle-db:/var/lib/mysql
    ports:
     - 3306:3306
    environment:
     <<: *db-variables
volumes:
  bugle-db:
