spring:
 application:
  name: NEWSPAPER
 datasource:
  url: jdbc:mysql://localhost:3306/bugle
  username: jjjjr
  passwrod: spiderman
  driver-class-name: com.mysql.cj.jdbc.Driver 
  platform: mysql
  flyway:
   baseline-on-migrate: true
   schemas: bugle
   user: ${spring.datasource.username}
   password: ${spring.datasource.url}