spring:
 application:
  name: NEWSPAPER
 thymeleaf:
  cache: false
  enabled: true
 datasource:
  url: jdbc:mysql://localhost:3306/bugle
  driver-class-name: com.mysql.cj.jdbc.Driver 
  platform: mysql
  flyway:
   baseline-on-migrate: true
   schemas: ['bugle']
   user: ${spring.datasource.username}
   password: ${spring.datasource.password}
   url: ${spring.datasource.url}
 server:
  port: 8080