spring:
 application:
  name: NEWSPAPER
 thymeleaf:
  cache: false
  enabled: true
 logging:
  level:
    org:
      springframework: TRACE
 datasource:
  url: jdbc:mysql://localhost:3306/bugle
  driver-class-name: com.mysql.cj.jdbc.Driver 
  platform: mysql
  username: jjjjr
  password: spiderman
  flyway:
   baseline-on-migrate: true
   schemas: ['bugle']
   user: ${spring.datasource.username}
   password: ${spring.datasource.password}
   url: ${spring.datasource.url}
 server:
  servlet:
   session:
    tracking-modes: cookie
  port: 8080
logging:
  level:
    org:
      springframework: 
        security: DEBUG